version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:2.11.1'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'

    volumes:
      - /opt/docker_data/nginxproxymanager/data:/data
      - /opt/docker_data/nginxproxymanager/letsencrypt:/etc/letsencrypt